### PR TITLE
fix!: update separators

### LINKED ISSUE #35: `toTitleCase` is removing full stops `.`
`console.log(toTitleCase('hello there old friend...'))`

Screenshot 2023-10-05 at 10 39 15

Maybe intentional? Not sure :)

### PR DESCRIPTION
**Pull request by jly36963**
Should Close #35

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -1,7 +1,36 @@
...
+] as const
+
+type Separator = (typeof SEPARATORS)[number]
+
+/** Escape characters with special significance in regular expressions */
+function escapeCharacter(char: string): string {
+  if (['[', ']', '{', '}', '(', ')', '|', '/', '-'].includes(char)) {
+    return `\\${char}`
+  }
+  return char
```
Comment (gustavoguichard) [inline src/utils.ts:27]: I miss the '\' character.
Also, maybe you could have:
```ts
const UNESCAPED_SEPARATORS = ['[', ']'] as const // ...
const SEPARATORS = join([UNESCAPED_SEPARATORS, [' ', '-'] as const]) // ...

/** Escape characters with special significance in regular expressions */
function escapeCharacter(char: string): string {
  if (UNESCAPED_SEPARATORS.includes(char)) {
    return `\\${char}`
  }
  return char
}
```

Just to make sure the next time we touch this array we are adding a separator in the right category.

File: src/utils.test.ts [hunk 2]
```diff
@@ -69,8 +69,23 @@ namespace WordsTests {
...
+      'five',
+      'six',
+      'seven',
+      'eight',
+      'nine',
+      'ten',
+    ] as const
+    const result = subject.words(
+      '[one] two-three/four.five(six){seven}|eight_nine\\ten',
+    )
```
Comment (gustavoguichard) [inline src/utils.test.ts:86]: good one!

File: src/casing.test.ts [hunk 3]
```diff
@@ -156,4 +156,65 @@ describe('casing functions', () => {
     expect(result).toEqual(expected)
     type test = Expect<Equal<typeof result, typeof expected>>
   })
+
+  describe('with various separators', () => {
+    const text =
+      '[one] two-three/four.five(six){seven}|eight_nine\\ten' as const
+
```
Comment (jly36963) [inline src/casing.test.ts:163]: I wish for a DRYer way to write this test suite -- they're all the exact same.

There isn't a way to do the following, is there?

```ts
const text = 'abc'

const resultExpectedMap = new Map([
  [subject.toUpperCase(text), 'ABC'],
  // ...
]) 

for (const [result, expected] in  resultExpectedMap.entries() {
  expect(result).toEqual(expected)
  type test = Expect<Equal<typeof result, typeof expected>>
}
```

Comment (jly36963) [reply src/casing.test.ts:163]: The closest I could get is this
Screenshot 2023-10-05 at 1 26 26 PM

Comment (jly36963) [reply src/casing.test.ts:163]: The problem is that I could switch `ABC` and `abc` on the expected side and the type union would still be equal

Comment (gustavoguichard) [reply src/casing.test.ts:163]: It could be easier... I personally am not a fan of too much abstractions in tests.. I tend to just repeat LOCs to avoid potential footguns.
But not against the trials

**Comment by gustavoguichard** [comment]
Lemme know when it is ready for review

**Review by gustavoguichard — APPROVED** [review]
